mybatis:
  mapper-locations: classpath:mapper/*
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.zjr.assistant.entities

server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 50MB #文件上传最大50M
      max-request-size: 50MB #请求大小最大50M
  #数据库配置
  datasource:
    url: jdbc:mysql://42.192.230.241:3306/assistant?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true
    username: root
    password: ZJR199925
    driver-class-name: com.mysql.cj.jdbc.Driver

    #druid连接池
    druid:
      initial-size: 5 #初始化连接数
      min-idle: 5 #最小连接数
      max-active: 20  #最大连接数
      max-wait: 60000 #超时等待时间
      time-between-eviction-runs-millis: 60000 #每隔隔一分钟检测关闭空闲连接
      min-evictable-idle-time-millis: 300000 #一个连接在池中最小生存时间
      stat-view-servlet:
        url-pattern: /druid/* #访问druid界面的url
        allow: 127.0.0.1  #配置IP白名单，如果不配置，则允许所有访问
        reset-enable: false #禁用HTML中的Rest All按钮
        #登录用户名/密码
#        login-username: root
#        login-password: ZJR199925
  #热部署配置
  devtools:
    restart:
      enabled: true #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: mapper/**
  freemarker:
    cache: false

  #redis缓存配置
  redis:
    database: 0 #数据库索引
    host: localhost #主机地址
    port: 6379 #端口
    password: #密码默认没有
    jedis:
      pool:
        max-active: 200 #连接池最大连接数
        max-wait: -1  #连接池最大阻塞等待时间
        max-idle: 10  #连接池最大空闲连接
        min-idle: 0   #连接池中最小空闲连接
    timeout: 1000 #超时时长限制msr
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 2759442036@qq.com
    password: wvzvnqtzadexdeja
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    root: warn
